version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - rabbitmq
    command: ["/bin/sh", "./init.sh", "npm", "run", "dev"]
    ports:
      - "3000:3000"

  consumer:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    command: ["/bin/sh", "./init.sh", "npm", "run", "start:consumers"]
    depends_on:
      - rabbitmq
      - backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "9000:9000"
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]
