version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  app:
    build: .
    volumes:
      - ./backend:/app
    depends_on:
      - rabbitmq
    command: ["/bin/sh", "./init.sh", "npm", "run", "dev"]
    ports:
      - "3000:3000"

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    command: ["/bin/sh", "./init.sh", "npm", "run", "start:consumers"]
    depends_on:
      - rabbitmq
      - app
